### PR TITLE
irq_latency code and design take from old embench-context-latency rep…

### PR DESCRIPTION
**Pull request by ronen-haen-sndk**
…ository

### CODE REVIEW

**Review by JulianKunkel — COMMENTED** [review]
The code for RISC-V is quite low-level with many assembler fragments and even a linker script.
The high-level design looks great.
I feel a bit that the further maintenance of the code will be a bit challenging.

**Comment by ronen-haen-sndk** [comment]
Well, some code fragments are indeed in assemble – I don’t see other option when measuring interrupt latency; similar was done with the context switch benchmark

**Comment by JulianKunkel** [comment]
Could you maybe add more code documentation inline?

**Comment by ronen-haen-sndk** [comment]
Can you provide an example, where are you missing documentation?

**Comment by JulianKunkel** [comment]
Regarding the usage of the different components, e.g., description with the justification of why these pieces are there, possibly that could go into the Makefile or the Markdown file.
The file irq_latency/source/bsp-rv-swerv-olof-eh1.c is an example where some code snippets would help.
Maybe for improving the code readability, a header file with all the psp_* functions could be created documenting there what it does then including in both the implementation and the usage? That would reduce the chance of typos and replication while providing documentation.

Just to clarify, I do understand the need for going low-level, and most code pieces individually are well documented. It is just that I believe maintenance is important and documentation will increase trust in the benchmark.

**Comment by ronen-haen-sndk** [comment]
Does your comment refers to this PR only or for the entire embench-rt (including the existing code for context switch)?
Currently, embench-rt contains no documentation (opposed to embench-iot)

**Comment by JulianKunkel** [comment]
I would argue that the PR should be self-contained and include documentation relevant for itself.  
Arguable the general documentation could be improved but that is different matter.

**Review by JulianKunkel — APPROVED** [review]
Great comments. 
I like the simplification of the linker script and the usage of the header file.

**Comment by jeremybennett** [comment]
Thanks for all the feedback and improvements. Good to merge.

**Pull request merged**
