### PR TITLE
new context switch benchmark

### PR DESCRIPTION
**Pull request by ronen-haen-sndk**

### CODE REVIEW

**Comment by bmcspadd-seagate** [comment]
Here are some general comments with regards to a context-switch benchmark....

    G1. What effects are we testing for?
        - Register save/restore.
        - Memory protection.
        - Cache effects.  Cache Management operations that must be
            done to flush/invalidate the cache.
        - Any other "CSR" changes that must be made.  These are different for
            each architecture.  Benchmark must easily allow for this.
        - Pipeline flush

    G2. What about a lightweight threads package?

        G3.1 Protothreads    http://dunkels.com/adam/pt/
            I've used protothreads in verification.  It was useful
            for what I was working on (coherency testing in a
            multi-processor environment),  but the functionality
            is limited.  Main limitation:  no stack-based variables.
            Well,  you can have them,  but they get corrupted.
            All variables need to be global.  meh.
     
    G3. In some ways,  a context switch is also a decent interrupt
        benchmark.  Much of the same stuff has to be done.

    G4. Within the benchmark,  we need a method whereby we can
        tease out just the performance of the context switch.
        We don't want to include perfance impact of the thread
        code that gets interrupted.

    G5. We should probably have several levels of context switching
        benchmarks:
            bare metal
            Basic memory protection (ala RISC-V PMPs)
            Virtual Memory (Machine/Supervisor/User modes)

**Comment by oferShinaar** [comment]
- G1:
    * The main target is to provide a generic test suite code written in C that models real cases from the RTOS world.
Vendors can use it to compare results on different targets.

        The code provides "porting," files so each target will need to modify these files only, no need to change the main suite. Currently, that will only be the activated counters for IPC calculation. Any target should have it for measurements.

    * Cache effects are not part of the test. one target can have it, and the other may not. That is the beauty it is target agnostics. 
    Embench test structure take care in making the cache warm before the test starts (if you have cache)


- G2: This is something to consider; maybe to add that to the next phase?
Currently, it is not part of this PR (this will be a change request in the requirements) 

- G3: Correct, but this suite is not interrupt-driven. It is a non-preemptive suite; only check context switch latency. 
For interrupts latency, we have this suite: https://github.com/embench/embench-rt/tree/main/irq_latency
Btw, we have results for this test suite (based on WDC Swerv core). We are waiting for the M3/M4 results so we can have a reference as the other Embench test suites results.
Feel free to check the suite and/or run it.

- G4: I agree, and this is how the suite was designed. Can you elaborate where you saw it or point us to this part in the test suite?

- G5: That is a good idea. Once the PR is approved, we can add on it as it will be the base structure for more flavors. 
    •	We just need to think how we can "modeling" / "simulate" PMP, VM, and privileges changes because we want to be target agnostics (e.g. ARM vs RV)
    •	Can you explain what you mean by "bare metal" in the aspects of context switch?

**Comment by oferShinaar** [comment]
are there any more questions, comments for this PR?
The PR is planned to be merged in Oct

**Comment by jeremybennett** [comment]
@oferShinaar Is there any reason why this should not be merged now. I see it is marked as awaiting review from @nati-rapaport.

**Comment by oferShinaar** [comment]
@jeremybennett I waited until Oct to give the last chance to comment on this issue. If no comments until the Embench meeting on 18/Oct I will merge it.

**Review by nati-rapaport — APPROVED** [review]

**Comment by nati-rapaport** [comment]
Merge context-switch benchmark test. No other comments have been received so far.
Following the [meeting minutes from October 2021](https://github.com/embench/embench-meetings/blob/main/meetings/2021/2021-10-18-minutes.md)

**Pull request merged**
